on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
      working-directory: ./app
    - uses: actions/upload-artifact@v6
      with:
          name: verademo.war
          path: app/target/verademo.war
        
  pipeline_scan:
      needs: build
      runs-on: ubuntu-latest
      name: Veracode Pipeline Scan
      steps:
        - name: checkout repo
          uses: actions/checkout@v6

        - name: get archive
          uses: actions/download-artifact@v6
          with:
            name: verademo.war
        - name: pipeline-scan action step
          id: pipeline-scan
          uses: veracode/Veracode-pipeline-scan-action@esd-true
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 
            veracode_policy_name: "Veracode Recommended Very High"
            debug: 1
            fail_build: false
        # - uses: actions/upload-artifact@v6
        #   with:
        #     name: Veracode Pipeline-Scan Results
        #     path: results.json
        
  results_to_sarif:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    name: Import Pipeline Results to SARIF
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        
      - name: Get scan results
        uses: actions/download-artifact@v6
        with:
          name: "Veracode Pipeline-Scan Results"
          
      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
        with:
          results-json: filtered_results.json
          output-results-sarif: veracode-results.sarif
          source-base-path-1: "^com/:src/main/java/com/"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
          repo_owner: ${{ github.repository_owner }}
          # repo_name: ${{ github.repository }}
          commitSHA: ${{ github.sha }}
          ref: ${{ github.ref }}
          githubToken: ${{ github.token }}

      - name: Upload SARIF
        id: upload
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: veracode-results.sarif
          category: pipeline-scan
          
  # veracode-fix:
  #   runs-on: ubuntu-latest
  #   needs: pipeline_scan
  #   name: Veracode Fix
  #   steps:
  #     - name: checkout repo
  #       uses: actions/checkout@v6
  
  #     - name: get flaw file
  #       uses: actions/download-artifact@v6
  #       with:
  #         name: Veracode Pipeline-Scan Results
          
  #     - name: Create fixes from static findings
  #       id: convert
  #       uses: Veracode/veracode-fix@main
  #       with:
  #         access_token: ${{ github.token }}
  #         inputFile: filtered_results.json
  #         vid: ${{ secrets.VID }}
  #         vkey: ${{ secrets.VKEY }}
  #         source_base_path_1: "com/:app/src/main/java/com/"
  #         source_base_path_2: "WEB-INF:app/src/main/webapp/WEB-INF"
  #         language: java
  #         prComment: true
  #         fixType: single
